### ISSUE TITLE
\Quote on Chapters

### ISSUE THREAD

**Issue by LudeeD** [fabiomaia/ua-thesis-template#11]
Maybe big noob on latex but the macro \Quote appears to not be usable in the Chapters

**Comment by rj-jesus** [comment]
Maybe try
```
\epigraph{Your quote.}{--- \textup{Author}, Publication}
```

**Comment by LudeeD** [comment]
Just said something because the macro is defined in the University template, however, cannot use it in Chapters because build fails

**Comment by rj-jesus** [comment]
The macro you're referring too is meant only for the cover. See particularly this excerpt from `uaThesisTemplate.sty`.

```
\newcommand{\Quote}[2]{\def\ciQuoteText{#1}\def\ciQuoteAuthor{#2}}

% ...

%
% Second alternative, with a citation
%
\ifdefined \ciQuoteText
  \TitlePage
    \HEADER{\BAR\FIG{
           \begin{minipage}{100mm} % no more than 120mm
            ``\textit{\ciQuoteText}''
             \begin{flushright}
	  	  	     --- \ciQuoteAuthor
             \end{flushright}
          \end{minipage}
          }}
           {\ciThesisYear}
   \dolistloop{\ciTitle}

  \EndTitlePage
  \titlepage\ \endtitlepage % empty page
\fi
```

The variables held in the macro are expanded accordingly and placed in the title page.
