### ISSUE TITLE
Subsection title in bold

### ISSUE THREAD

**Issue by LudeeD** [fabiomaia/ua-thesis-template#15]
Is this the expected behavior ?

![Screenshot from 2019-03-18 14-02-57](https://user-images.githubusercontent.com/9322214/54535596-bf926b00-4986-11e9-91e5-cc37545c77c7.png)

**Comment by LudeeD** [comment]
Ok, I believe that the default chapterstyle used is "veelo" and we are not even using the file "custom-theme.tex"

**Comment by rj-jesus** [comment]
@LudeeD 8 days late, but to add on to this, the image you posted is the expected behavior with the theme you are using.

As far as I known we are free to use any theme with any font(s) we want __in the matter of the thesis__. Only the cover may not be changed (well, apart form the font).
