### ISSUE TITLE
How do i remove "documento provisório"

### ISSUE THREAD

**Issue by stormsz** [fabiomaia/ua-thesis-template#16]
hey, so my professor wants me to use the UA latex template, the problem is that i'm a noob on latex and cant figure out how to remove the "documento provisório".

been studying latex for the past week, working great so far, but i just cant find where to delete that.

**Comment by rj-jesus** [comment]
Hi

If I'm not mistaken you just have to add `final` to the options of the UA template style.

So, in the file `cover.tex` simply change
```
\usepackage[engineering,deti]{uaThesisTemplate}
```
to
```
\usepackage[engineering,deti,final]{uaThesisTemplate}
```
(with whatever other options you may have adjusted).

--
Ricardo Jesus

**Comment by stormsz** [comment]
Yes! that fixed it!

thanks a lot Ricardo.
